fabric8-et: gosu and postgres activated

diff --git a/postchain-containerized/src/main/docker/Dockerfile b/postchain-containerized/src/main/docker/Dockerfile
--- a/postchain-containerized/src/main/docker/Dockerfile
+++ b/postchain-containerized/src/main/docker/Dockerfile
@@ -9,33 +9,33 @@ RUN apk add openjdk8
 # Install bash, curl
 RUN apk update && apk add bash curl
 
-#ENV GOSU_VERSION 1.13
-#RUN set -eux; \
-#  \
-#  apk add --no-cache --virtual .gosu-deps \
-#  ca-certificates \
-#  dpkg \
-#  gnupg \
-#  ; \
-#  \
-#  dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
-#  wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
-#  wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
-#  \
-#  # verify the signature
-#  export GNUPGHOME="$(mktemp -d)"; \
-#  gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
-#  gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
-#  command -v gpgconf && gpgconf --kill all || :; \
-#  rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
-#  \
-#  # clean up fetch dependencies
-#  apk del --no-network .gosu-deps; \
-#  \
-#  chmod +x /usr/local/bin/gosu; \
-#  # verify that the binary works
-#  gosu --version; \
-#  gosu nobody true
+ENV GOSU_VERSION 1.13
+RUN set -eux; \
+  \
+  apk add --no-cache --virtual .gosu-deps \
+  ca-certificates \
+  dpkg \
+  gnupg \
+  ; \
+  \
+  dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+  wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+  wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+  \
+  # verify the signature
+  export GNUPGHOME="$(mktemp -d)"; \
+  gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+  gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+  command -v gpgconf && gpgconf --kill all || :; \
+  rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+  \
+  # clean up fetch dependencies
+  apk del --no-network .gosu-deps; \
+  \
+  chmod +x /usr/local/bin/gosu; \
+  # verify that the binary works
+  gosu --version; \
+  gosu nobody true
 
 ENV POSTGRES_DB=postchain
 ENV POSTGRES_USER=postchain
